name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Setup Yarn
      # You may pin to the exact commit or the version.
      # uses: mskelton/setup-yarn@2fd0f48147cbee4fd8a71723a3b86851d86ba46b
      uses: mskelton/setup-yarn@v1.4.0
      with:
        # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
        cache: yarn
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'Dwigoric'
        reponame: 'CCAPDEV-Web-App'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        
